### ISSUE TITLE
Deployment Issue related to VTAP service

### ISSUE THREAD

**Issue by nc-oci** [oracle-quickstart/oci-scca-landingzone#8]
We have identified a deployment issue in OC1 Region related to the VTAP feature as it has been temporarily disabled. 
Error: 404-NotAuthorizedOrNotFound, NotAuthorizedOrNotFound

The following resources are not available:
https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_capture_filter
https://docs.oracle.com/iaas/api/#/en/iaas/20160918/CaptureFilter/CreateCaptureFilter

This is due to the fact that all VTAP service management operations (Create, Update, List, Get & Delete) are currently disabled.   Please reach out to Oracle Customer Support if you should have any questions related to VTAP service issues.

**Comment by VinayKumar611** [comment]
We had new variable to enable or disable VTAP service deployment. 
Variable : is_vtap_enabled(boolean)
Default Value : true (i.e. VTAP service will be deployed)

If the end users decided not to deploy the VTAP service , they can set the variable to false on the tfvars file(CLI Deployment)
is_vtap_enabled        = false

Fix is there on the integration branch*. 
https://github.com/oracle-quickstart/oci-scca-landingzone/tree/integration 

*PS : integration branch is not end to end tested.
